/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  PagedUsuarioSchema,
  UsuarioApiListarUsuariosParams,
  UsuarioCambiarMiContrasenaSchema,
  UsuarioCreateSchema,
  UsuarioRestablecerContrasenaSchema,
  UsuarioSchema
} from './schemas';

/**
 * @summary Listar Usuarios
 */
export type usuarioApiListarUsuariosResponse200 = {
  data: PagedUsuarioSchema
  status: 200
}
    
export type usuarioApiListarUsuariosResponseSuccess = (usuarioApiListarUsuariosResponse200) & {
  headers: Headers;
};
;

export type usuarioApiListarUsuariosResponse = (usuarioApiListarUsuariosResponseSuccess)

export const getUsuarioApiListarUsuariosUrl = (params?: UsuarioApiListarUsuariosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/usuarios/listar?${stringifiedParams}` : `/api/usuarios/listar`
}

export const usuarioApiListarUsuarios = async (params?: UsuarioApiListarUsuariosParams, options?: RequestInit): Promise<usuarioApiListarUsuariosResponse> => {
  
  const res = await fetch(getUsuarioApiListarUsuariosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiListarUsuariosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiListarUsuariosResponse
}



/**
 * @summary Crear Usuario
 */
export type usuarioApiCrearUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}
    
export type usuarioApiCrearUsuarioResponseSuccess = (usuarioApiCrearUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiCrearUsuarioResponse = (usuarioApiCrearUsuarioResponseSuccess)

export const getUsuarioApiCrearUsuarioUrl = () => {


  

  return `/api/usuarios/crear`
}

export const usuarioApiCrearUsuario = async (usuarioCreateSchema: UsuarioCreateSchema, options?: RequestInit): Promise<usuarioApiCrearUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiCrearUsuarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiCrearUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiCrearUsuarioResponse
}



/**
 * @summary Eliminar Usuario
 */
export type usuarioApiEliminarUsuarioResponse200 = {
  data: void
  status: 200
}
    
export type usuarioApiEliminarUsuarioResponseSuccess = (usuarioApiEliminarUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiEliminarUsuarioResponse = (usuarioApiEliminarUsuarioResponseSuccess)

export const getUsuarioApiEliminarUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/eliminar/${usuarioId}`
}

export const usuarioApiEliminarUsuario = async (usuarioId: number, options?: RequestInit): Promise<usuarioApiEliminarUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiEliminarUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiEliminarUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiEliminarUsuarioResponse
}



/**
 * @summary Restablecer Contrasena Usuario
 */
export type usuarioApiRestablecerContrasenaUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}
    
export type usuarioApiRestablecerContrasenaUsuarioResponseSuccess = (usuarioApiRestablecerContrasenaUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuarioApiRestablecerContrasenaUsuarioResponse = (usuarioApiRestablecerContrasenaUsuarioResponseSuccess)

export const getUsuarioApiRestablecerContrasenaUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/restablecer_contrasena/${usuarioId}`
}

export const usuarioApiRestablecerContrasenaUsuario = async (usuarioId: number,
    usuarioRestablecerContrasenaSchema: UsuarioRestablecerContrasenaSchema, options?: RequestInit): Promise<usuarioApiRestablecerContrasenaUsuarioResponse> => {
  
  const res = await fetch(getUsuarioApiRestablecerContrasenaUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioRestablecerContrasenaSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiRestablecerContrasenaUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiRestablecerContrasenaUsuarioResponse
}



/**
 * @summary Cambiar Mi Contrasena
 */
export type usuarioApiCambiarMiContrasenaResponse200 = {
  data: UsuarioSchema
  status: 200
}
    
export type usuarioApiCambiarMiContrasenaResponseSuccess = (usuarioApiCambiarMiContrasenaResponse200) & {
  headers: Headers;
};
;

export type usuarioApiCambiarMiContrasenaResponse = (usuarioApiCambiarMiContrasenaResponseSuccess)

export const getUsuarioApiCambiarMiContrasenaUrl = () => {


  

  return `/api/usuarios/cambiar_mi_contrasena`
}

export const usuarioApiCambiarMiContrasena = async (usuarioCambiarMiContrasenaSchema: UsuarioCambiarMiContrasenaSchema, options?: RequestInit): Promise<usuarioApiCambiarMiContrasenaResponse> => {
  
  const res = await fetch(getUsuarioApiCambiarMiContrasenaUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioCambiarMiContrasenaSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuarioApiCambiarMiContrasenaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuarioApiCambiarMiContrasenaResponse
}
