/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export * from './input';
export * from './localApiListarLocalesParams';
export * from './localAsignadoSchema';
export * from './localCreateSchema';
export * from './localSchema';
export * from './localUpdateSchema';
export * from './localUsuarioLocalApiListarUsuariosConLocalesParams';
export * from './pagedLocalSchema';
export * from './pagedProductoSchema';
export * from './pagedUsuarioConLocalesSchema';
export * from './productoApiListarProductosParams';
export * from './productoCreateSchema';
export * from './productoSchema';
export * from './productoUpdateSchema';
export * from './usuarioConLocalesSchema';
export * from './usuarioLocalPayloadSchema';