/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type { LocalSchema } from './localSchema';

export interface PagedLocalSchema {
  items: LocalSchema[];
  count: number;
}
