/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  /** @maxLength 255 */
  nombre: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  precio: string;
  cuenta: number;
}
