/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type { LocalAsignadoSchema } from './localAsignadoSchema';

export interface UsuarioConLocalesSchema {
  usuario_id: number;
  email: string;
  es_admin: boolean;
  locales: LocalAsignadoSchema[];
}
