/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  PagedProductoSchema,
  ProductoApiListarProductosParams,
  ProductoSchema,
  ProductoUpdateSchema
} from './schemas';

/**
 * @summary Listar Productos
 */
export type productoApiListarProductosResponse200 = {
  data: PagedProductoSchema
  status: 200
}
    
export type productoApiListarProductosResponseSuccess = (productoApiListarProductosResponse200) & {
  headers: Headers;
};
;

export type productoApiListarProductosResponse = (productoApiListarProductosResponseSuccess)

export const getProductoApiListarProductosUrl = (params?: ProductoApiListarProductosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/productos/listar?${stringifiedParams}` : `/api/productos/listar`
}

export const productoApiListarProductos = async (params?: ProductoApiListarProductosParams, options?: RequestInit): Promise<productoApiListarProductosResponse> => {
  
  const res = await fetch(getProductoApiListarProductosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiListarProductosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiListarProductosResponse
}



/**
 * @summary Actualizar Producto
 */
export type productoApiActualizarProductoResponse200 = {
  data: ProductoSchema
  status: 200
}
    
export type productoApiActualizarProductoResponseSuccess = (productoApiActualizarProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiActualizarProductoResponse = (productoApiActualizarProductoResponseSuccess)

export const getProductoApiActualizarProductoUrl = (productoId: number,) => {


  

  return `/api/productos/actualizar/${productoId}`
}

export const productoApiActualizarProducto = async (productoId: number,
    productoUpdateSchema: ProductoUpdateSchema, options?: RequestInit): Promise<productoApiActualizarProductoResponse> => {
  
  const res = await fetch(getProductoApiActualizarProductoUrl(productoId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      productoUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiActualizarProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiActualizarProductoResponse
}



/**
 * @summary Eliminar Producto
 */
export type productoApiEliminarProductoResponse200 = {
  data: void
  status: 200
}
    
export type productoApiEliminarProductoResponseSuccess = (productoApiEliminarProductoResponse200) & {
  headers: Headers;
};
;

export type productoApiEliminarProductoResponse = (productoApiEliminarProductoResponseSuccess)

export const getProductoApiEliminarProductoUrl = (productoId: number,) => {


  

  return `/api/productos/eliminar/${productoId}`
}

export const productoApiEliminarProducto = async (productoId: number, options?: RequestInit): Promise<productoApiEliminarProductoResponse> => {
  
  const res = await fetch(getProductoApiEliminarProductoUrl(productoId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productoApiEliminarProductoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productoApiEliminarProductoResponse
}
