/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface LoginResponseSchema {
  token: string;
  usuario_id: number;
  email: string;
  es_admin: boolean;
}
