/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  PagedUnidadMedidaSchema,
  UnidadMedidaApiListarUnidadesParams,
  UnidadMedidaCreateSchema,
  UnidadMedidaSchema,
  UnidadMedidaUpdateSchema
} from './schemas';

/**
 * @summary Listar Unidades
 */
export type unidadMedidaApiListarUnidadesResponse200 = {
  data: PagedUnidadMedidaSchema
  status: 200
}
    
export type unidadMedidaApiListarUnidadesResponseSuccess = (unidadMedidaApiListarUnidadesResponse200) & {
  headers: Headers;
};
;

export type unidadMedidaApiListarUnidadesResponse = (unidadMedidaApiListarUnidadesResponseSuccess)

export const getUnidadMedidaApiListarUnidadesUrl = (params?: UnidadMedidaApiListarUnidadesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/unidades-medida/listar?${stringifiedParams}` : `/api/unidades-medida/listar`
}

export const unidadMedidaApiListarUnidades = async (params?: UnidadMedidaApiListarUnidadesParams, options?: RequestInit): Promise<unidadMedidaApiListarUnidadesResponse> => {
  
  const res = await fetch(getUnidadMedidaApiListarUnidadesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: unidadMedidaApiListarUnidadesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as unidadMedidaApiListarUnidadesResponse
}



/**
 * @summary Crear Unidad
 */
export type unidadMedidaApiCrearUnidadResponse200 = {
  data: UnidadMedidaSchema
  status: 200
}
    
export type unidadMedidaApiCrearUnidadResponseSuccess = (unidadMedidaApiCrearUnidadResponse200) & {
  headers: Headers;
};
;

export type unidadMedidaApiCrearUnidadResponse = (unidadMedidaApiCrearUnidadResponseSuccess)

export const getUnidadMedidaApiCrearUnidadUrl = () => {


  

  return `/api/unidades-medida/crear`
}

export const unidadMedidaApiCrearUnidad = async (unidadMedidaCreateSchema: UnidadMedidaCreateSchema, options?: RequestInit): Promise<unidadMedidaApiCrearUnidadResponse> => {
  
  const res = await fetch(getUnidadMedidaApiCrearUnidadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      unidadMedidaCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: unidadMedidaApiCrearUnidadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as unidadMedidaApiCrearUnidadResponse
}



/**
 * @summary Actualizar Unidad
 */
export type unidadMedidaApiActualizarUnidadResponse200 = {
  data: UnidadMedidaSchema
  status: 200
}
    
export type unidadMedidaApiActualizarUnidadResponseSuccess = (unidadMedidaApiActualizarUnidadResponse200) & {
  headers: Headers;
};
;

export type unidadMedidaApiActualizarUnidadResponse = (unidadMedidaApiActualizarUnidadResponseSuccess)

export const getUnidadMedidaApiActualizarUnidadUrl = (unidadId: number,) => {


  

  return `/api/unidades-medida/actualizar/${unidadId}`
}

export const unidadMedidaApiActualizarUnidad = async (unidadId: number,
    unidadMedidaUpdateSchema: UnidadMedidaUpdateSchema, options?: RequestInit): Promise<unidadMedidaApiActualizarUnidadResponse> => {
  
  const res = await fetch(getUnidadMedidaApiActualizarUnidadUrl(unidadId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      unidadMedidaUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: unidadMedidaApiActualizarUnidadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as unidadMedidaApiActualizarUnidadResponse
}



/**
 * @summary Eliminar Unidad
 */
export type unidadMedidaApiEliminarUnidadResponse200 = {
  data: void
  status: 200
}
    
export type unidadMedidaApiEliminarUnidadResponseSuccess = (unidadMedidaApiEliminarUnidadResponse200) & {
  headers: Headers;
};
;

export type unidadMedidaApiEliminarUnidadResponse = (unidadMedidaApiEliminarUnidadResponseSuccess)

export const getUnidadMedidaApiEliminarUnidadUrl = (unidadId: number,) => {


  

  return `/api/unidades-medida/eliminar/${unidadId}`
}

export const unidadMedidaApiEliminarUnidad = async (unidadId: number, options?: RequestInit): Promise<unidadMedidaApiEliminarUnidadResponse> => {
  
  const res = await fetch(getUnidadMedidaApiEliminarUnidadUrl(unidadId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: unidadMedidaApiEliminarUnidadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as unidadMedidaApiEliminarUnidadResponse
}
