/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export type ConteostockApiListaComprasLocalParams = {
local_id: number;
fecha?: string | null;
};
