/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export type ConteostockApiListarConteosParams = {
local_id?: number | null;
fecha?: string | null;
/**
 * @minimum 1
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
