/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface ConteoStockSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  local: number;
  fecha?: string;
  /** @maxLength 20 */
  estado?: string;
  creado_por?: number | null;
}
