/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface ItemListaCompraTotalSchema {
  producto_id: number;
  producto_nombre: string;
  cantidad_a_comprar: number;
}
