/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface ItemConteoStockSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  conteo_stock: number;
  producto: number;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  cantidad_conteada: string;
}
