/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface ItemListaCompraSchema {
  producto_id: number;
  producto_nombre: string;
  cantidad_objetivo: number;
  cantidad_actual: number;
  cantidad_a_comprar: number;
}
