/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ItemListaCompraTotalSchema } from './itemListaCompraTotalSchema';
import type { LocalSinConteoSchema } from './localSinConteoSchema';

export interface ListaCompraTotalSchema {
  fecha: string;
  items: ItemListaCompraTotalSchema[];
  locales_sin_conteo_finalizado: LocalSinConteoSchema[];
}
