/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ItemListaCompraSchema } from './itemListaCompraSchema';

export interface ListaCompraLocalSchema {
  local_id: number;
  local_nombre: string;
  fecha: string;
  items: ItemListaCompraSchema[];
}
