/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type { ConteoStockSchema } from './conteoStockSchema';

export interface PagedConteoStockSchema {
  items: ConteoStockSchema[];
  count: number;
}
