/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type { LocalSinConteoSchema } from './localSinConteoSchema';
import type { ResumenConteoSchema } from './resumenConteoSchema';

export interface ResumenLocalFechaSchema {
  fecha: string;
  locales: ResumenConteoSchema[];
  locales_sin_conteo_finalizado: LocalSinConteoSchema[];
}
