/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  DashboardSchema
} from './schemas';

/**
 * @summary Obtener Estadisticas
 */
export type dashboardApiObtenerEstadisticasResponse200 = {
  data: DashboardSchema
  status: 200
}
    
export type dashboardApiObtenerEstadisticasResponseSuccess = (dashboardApiObtenerEstadisticasResponse200) & {
  headers: Headers;
};
;

export type dashboardApiObtenerEstadisticasResponse = (dashboardApiObtenerEstadisticasResponseSuccess)

export const getDashboardApiObtenerEstadisticasUrl = () => {


  

  return `/api/dashboard/estadisticas`
}

export const dashboardApiObtenerEstadisticas = async ( options?: RequestInit): Promise<dashboardApiObtenerEstadisticasResponse> => {
  
  const res = await fetch(getDashboardApiObtenerEstadisticasUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: dashboardApiObtenerEstadisticasResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as dashboardApiObtenerEstadisticasResponse
}
