/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  ConteoStockCreateSchema,
  ConteoStockSchema,
  ConteoStockUpdateSchema,
  ConteostockApiListaComprasLocalParams,
  ConteostockApiListaComprasTotalParams,
  ConteostockApiListarConteosParams,
  ItemConteoStockCreateSchema,
  ItemConteoStockSchema,
  ItemConteoStockUpdateSchema,
  ItemListaCompraTotalSchema,
  ListaCompraLocalSchema,
  PagedConteoStockSchema,
  ResumenConteoSchema
} from './schemas';

/**
 * @summary Listar Conteos
 */
export type conteostockApiListarConteosResponse200 = {
  data: PagedConteoStockSchema
  status: 200
}
    
export type conteostockApiListarConteosResponseSuccess = (conteostockApiListarConteosResponse200) & {
  headers: Headers;
};
;

export type conteostockApiListarConteosResponse = (conteostockApiListarConteosResponseSuccess)

export const getConteostockApiListarConteosUrl = (params?: ConteostockApiListarConteosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/conteos-stock/listar?${stringifiedParams}` : `/api/conteos-stock/listar`
}

export const conteostockApiListarConteos = async (params?: ConteostockApiListarConteosParams, options?: RequestInit): Promise<conteostockApiListarConteosResponse> => {
  
  const res = await fetch(getConteostockApiListarConteosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiListarConteosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiListarConteosResponse
}



/**
 * @summary Obtener Conteo
 */
export type conteostockApiObtenerConteoResponse200 = {
  data: ConteoStockSchema
  status: 200
}
    
export type conteostockApiObtenerConteoResponseSuccess = (conteostockApiObtenerConteoResponse200) & {
  headers: Headers;
};
;

export type conteostockApiObtenerConteoResponse = (conteostockApiObtenerConteoResponseSuccess)

export const getConteostockApiObtenerConteoUrl = (conteoId: number,) => {


  

  return `/api/conteos-stock/obtener/${conteoId}`
}

export const conteostockApiObtenerConteo = async (conteoId: number, options?: RequestInit): Promise<conteostockApiObtenerConteoResponse> => {
  
  const res = await fetch(getConteostockApiObtenerConteoUrl(conteoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiObtenerConteoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiObtenerConteoResponse
}



/**
 * @summary Crear Conteo
 */
export type conteostockApiCrearConteoResponse200 = {
  data: ConteoStockSchema
  status: 200
}
    
export type conteostockApiCrearConteoResponseSuccess = (conteostockApiCrearConteoResponse200) & {
  headers: Headers;
};
;

export type conteostockApiCrearConteoResponse = (conteostockApiCrearConteoResponseSuccess)

export const getConteostockApiCrearConteoUrl = () => {


  

  return `/api/conteos-stock/crear`
}

export const conteostockApiCrearConteo = async (conteoStockCreateSchema: ConteoStockCreateSchema, options?: RequestInit): Promise<conteostockApiCrearConteoResponse> => {
  
  const res = await fetch(getConteostockApiCrearConteoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      conteoStockCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiCrearConteoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiCrearConteoResponse
}



/**
 * @summary Actualizar Conteo
 */
export type conteostockApiActualizarConteoResponse200 = {
  data: ConteoStockSchema
  status: 200
}
    
export type conteostockApiActualizarConteoResponseSuccess = (conteostockApiActualizarConteoResponse200) & {
  headers: Headers;
};
;

export type conteostockApiActualizarConteoResponse = (conteostockApiActualizarConteoResponseSuccess)

export const getConteostockApiActualizarConteoUrl = (conteoId: number,) => {


  

  return `/api/conteos-stock/actualizar/${conteoId}`
}

export const conteostockApiActualizarConteo = async (conteoId: number,
    conteoStockUpdateSchema: ConteoStockUpdateSchema, options?: RequestInit): Promise<conteostockApiActualizarConteoResponse> => {
  
  const res = await fetch(getConteostockApiActualizarConteoUrl(conteoId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      conteoStockUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiActualizarConteoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiActualizarConteoResponse
}



/**
 * @summary Finalizar Conteo
 */
export type conteostockApiFinalizarConteoResponse200 = {
  data: ConteoStockSchema
  status: 200
}
    
export type conteostockApiFinalizarConteoResponseSuccess = (conteostockApiFinalizarConteoResponse200) & {
  headers: Headers;
};
;

export type conteostockApiFinalizarConteoResponse = (conteostockApiFinalizarConteoResponseSuccess)

export const getConteostockApiFinalizarConteoUrl = (conteoId: number,) => {


  

  return `/api/conteos-stock/finalizar/${conteoId}`
}

export const conteostockApiFinalizarConteo = async (conteoId: number, options?: RequestInit): Promise<conteostockApiFinalizarConteoResponse> => {
  
  const res = await fetch(getConteostockApiFinalizarConteoUrl(conteoId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiFinalizarConteoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiFinalizarConteoResponse
}



/**
 * @summary Eliminar Conteo
 */
export type conteostockApiEliminarConteoResponse200 = {
  data: void
  status: 200
}
    
export type conteostockApiEliminarConteoResponseSuccess = (conteostockApiEliminarConteoResponse200) & {
  headers: Headers;
};
;

export type conteostockApiEliminarConteoResponse = (conteostockApiEliminarConteoResponseSuccess)

export const getConteostockApiEliminarConteoUrl = (conteoId: number,) => {


  

  return `/api/conteos-stock/eliminar/${conteoId}`
}

export const conteostockApiEliminarConteo = async (conteoId: number, options?: RequestInit): Promise<conteostockApiEliminarConteoResponse> => {
  
  const res = await fetch(getConteostockApiEliminarConteoUrl(conteoId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiEliminarConteoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiEliminarConteoResponse
}



/**
 * @summary Listar Items
 */
export type conteostockApiListarItemsResponse200 = {
  data: ItemConteoStockSchema[]
  status: 200
}
    
export type conteostockApiListarItemsResponseSuccess = (conteostockApiListarItemsResponse200) & {
  headers: Headers;
};
;

export type conteostockApiListarItemsResponse = (conteostockApiListarItemsResponseSuccess)

export const getConteostockApiListarItemsUrl = (conteoId: number,) => {


  

  return `/api/conteos-stock/items/listar/${conteoId}`
}

export const conteostockApiListarItems = async (conteoId: number, options?: RequestInit): Promise<conteostockApiListarItemsResponse> => {
  
  const res = await fetch(getConteostockApiListarItemsUrl(conteoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiListarItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiListarItemsResponse
}



/**
 * @summary Crear Item
 */
export type conteostockApiCrearItemResponse200 = {
  data: ItemConteoStockSchema
  status: 200
}
    
export type conteostockApiCrearItemResponseSuccess = (conteostockApiCrearItemResponse200) & {
  headers: Headers;
};
;

export type conteostockApiCrearItemResponse = (conteostockApiCrearItemResponseSuccess)

export const getConteostockApiCrearItemUrl = () => {


  

  return `/api/conteos-stock/items/crear`
}

export const conteostockApiCrearItem = async (itemConteoStockCreateSchema: ItemConteoStockCreateSchema, options?: RequestInit): Promise<conteostockApiCrearItemResponse> => {
  
  const res = await fetch(getConteostockApiCrearItemUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      itemConteoStockCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiCrearItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiCrearItemResponse
}



/**
 * @summary Actualizar Item
 */
export type conteostockApiActualizarItemResponse200 = {
  data: ItemConteoStockSchema
  status: 200
}
    
export type conteostockApiActualizarItemResponseSuccess = (conteostockApiActualizarItemResponse200) & {
  headers: Headers;
};
;

export type conteostockApiActualizarItemResponse = (conteostockApiActualizarItemResponseSuccess)

export const getConteostockApiActualizarItemUrl = (itemId: number,) => {


  

  return `/api/conteos-stock/items/actualizar/${itemId}`
}

export const conteostockApiActualizarItem = async (itemId: number,
    itemConteoStockUpdateSchema: ItemConteoStockUpdateSchema, options?: RequestInit): Promise<conteostockApiActualizarItemResponse> => {
  
  const res = await fetch(getConteostockApiActualizarItemUrl(itemId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      itemConteoStockUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiActualizarItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiActualizarItemResponse
}



/**
 * @summary Eliminar Item
 */
export type conteostockApiEliminarItemResponse200 = {
  data: void
  status: 200
}
    
export type conteostockApiEliminarItemResponseSuccess = (conteostockApiEliminarItemResponse200) & {
  headers: Headers;
};
;

export type conteostockApiEliminarItemResponse = (conteostockApiEliminarItemResponseSuccess)

export const getConteostockApiEliminarItemUrl = (itemId: number,) => {


  

  return `/api/conteos-stock/items/eliminar/${itemId}`
}

export const conteostockApiEliminarItem = async (itemId: number, options?: RequestInit): Promise<conteostockApiEliminarItemResponse> => {
  
  const res = await fetch(getConteostockApiEliminarItemUrl(itemId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiEliminarItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiEliminarItemResponse
}



/**
 * @summary Lista Compras Local
 */
export type conteostockApiListaComprasLocalResponse200 = {
  data: ListaCompraLocalSchema
  status: 200
}
    
export type conteostockApiListaComprasLocalResponseSuccess = (conteostockApiListaComprasLocalResponse200) & {
  headers: Headers;
};
;

export type conteostockApiListaComprasLocalResponse = (conteostockApiListaComprasLocalResponseSuccess)

export const getConteostockApiListaComprasLocalUrl = (params: ConteostockApiListaComprasLocalParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/conteos-stock/comprar/local?${stringifiedParams}` : `/api/conteos-stock/comprar/local`
}

export const conteostockApiListaComprasLocal = async (params: ConteostockApiListaComprasLocalParams, options?: RequestInit): Promise<conteostockApiListaComprasLocalResponse> => {
  
  const res = await fetch(getConteostockApiListaComprasLocalUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiListaComprasLocalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiListaComprasLocalResponse
}



/**
 * @summary Lista Compras Total
 */
export type conteostockApiListaComprasTotalResponse200 = {
  data: ItemListaCompraTotalSchema[]
  status: 200
}
    
export type conteostockApiListaComprasTotalResponseSuccess = (conteostockApiListaComprasTotalResponse200) & {
  headers: Headers;
};
;

export type conteostockApiListaComprasTotalResponse = (conteostockApiListaComprasTotalResponseSuccess)

export const getConteostockApiListaComprasTotalUrl = (params?: ConteostockApiListaComprasTotalParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/conteos-stock/comprar/total?${stringifiedParams}` : `/api/conteos-stock/comprar/total`
}

export const conteostockApiListaComprasTotal = async (params?: ConteostockApiListaComprasTotalParams, options?: RequestInit): Promise<conteostockApiListaComprasTotalResponse> => {
  
  const res = await fetch(getConteostockApiListaComprasTotalUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiListaComprasTotalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiListaComprasTotalResponse
}



/**
 * @summary Resumen Conteo
 */
export type conteostockApiResumenConteoResponse200 = {
  data: ResumenConteoSchema
  status: 200
}
    
export type conteostockApiResumenConteoResponseSuccess = (conteostockApiResumenConteoResponse200) & {
  headers: Headers;
};
;

export type conteostockApiResumenConteoResponse = (conteostockApiResumenConteoResponseSuccess)

export const getConteostockApiResumenConteoUrl = (conteoId: number,) => {


  

  return `/api/conteos-stock/resumen/${conteoId}`
}

export const conteostockApiResumenConteo = async (conteoId: number, options?: RequestInit): Promise<conteostockApiResumenConteoResponse> => {
  
  const res = await fetch(getConteostockApiResumenConteoUrl(conteoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: conteostockApiResumenConteoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as conteostockApiResumenConteoResponse
}
