/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  LocalApiListarLocalesParams,
  LocalCreateSchema,
  LocalSchema,
  LocalUpdateSchema,
  LocalUsuarioLocalApiListarUsuariosConLocalesParams,
  PagedLocalSchema,
  PagedUsuarioConLocalesSchema,
  UsuarioConLocalesSchema,
  UsuarioLocalPayloadSchema
} from './schemas';

/**
 * @summary Listar Locales
 */
export type localApiListarLocalesResponse200 = {
  data: PagedLocalSchema
  status: 200
}
    
export type localApiListarLocalesResponseSuccess = (localApiListarLocalesResponse200) & {
  headers: Headers;
};
;

export type localApiListarLocalesResponse = (localApiListarLocalesResponseSuccess)

export const getLocalApiListarLocalesUrl = (params?: LocalApiListarLocalesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/locales/listar?${stringifiedParams}` : `/api/locales/listar`
}

export const localApiListarLocales = async (params?: LocalApiListarLocalesParams, options?: RequestInit): Promise<localApiListarLocalesResponse> => {
  
  const res = await fetch(getLocalApiListarLocalesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: localApiListarLocalesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as localApiListarLocalesResponse
}



/**
 * @summary Crear Local
 */
export type localApiCrearLocalResponse200 = {
  data: LocalSchema
  status: 200
}
    
export type localApiCrearLocalResponseSuccess = (localApiCrearLocalResponse200) & {
  headers: Headers;
};
;

export type localApiCrearLocalResponse = (localApiCrearLocalResponseSuccess)

export const getLocalApiCrearLocalUrl = () => {


  

  return `/api/locales/crear`
}

export const localApiCrearLocal = async (localCreateSchema: LocalCreateSchema, options?: RequestInit): Promise<localApiCrearLocalResponse> => {
  
  const res = await fetch(getLocalApiCrearLocalUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      localCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: localApiCrearLocalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as localApiCrearLocalResponse
}



/**
 * @summary Actualizar Local
 */
export type localApiActualizarLocalResponse200 = {
  data: LocalSchema
  status: 200
}
    
export type localApiActualizarLocalResponseSuccess = (localApiActualizarLocalResponse200) & {
  headers: Headers;
};
;

export type localApiActualizarLocalResponse = (localApiActualizarLocalResponseSuccess)

export const getLocalApiActualizarLocalUrl = (localId: number,) => {


  

  return `/api/locales/actualizar/${localId}`
}

export const localApiActualizarLocal = async (localId: number,
    localUpdateSchema: LocalUpdateSchema, options?: RequestInit): Promise<localApiActualizarLocalResponse> => {
  
  const res = await fetch(getLocalApiActualizarLocalUrl(localId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      localUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: localApiActualizarLocalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as localApiActualizarLocalResponse
}



/**
 * @summary Eliminar Local
 */
export type localApiEliminarLocalResponse200 = {
  data: void
  status: 200
}
    
export type localApiEliminarLocalResponseSuccess = (localApiEliminarLocalResponse200) & {
  headers: Headers;
};
;

export type localApiEliminarLocalResponse = (localApiEliminarLocalResponseSuccess)

export const getLocalApiEliminarLocalUrl = (localId: number,) => {


  

  return `/api/locales/eliminar/${localId}`
}

export const localApiEliminarLocal = async (localId: number, options?: RequestInit): Promise<localApiEliminarLocalResponse> => {
  
  const res = await fetch(getLocalApiEliminarLocalUrl(localId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: localApiEliminarLocalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as localApiEliminarLocalResponse
}



/**
 * @summary Listar Usuarios Con Locales
 */
export type localUsuarioLocalApiListarUsuariosConLocalesResponse200 = {
  data: PagedUsuarioConLocalesSchema
  status: 200
}
    
export type localUsuarioLocalApiListarUsuariosConLocalesResponseSuccess = (localUsuarioLocalApiListarUsuariosConLocalesResponse200) & {
  headers: Headers;
};
;

export type localUsuarioLocalApiListarUsuariosConLocalesResponse = (localUsuarioLocalApiListarUsuariosConLocalesResponseSuccess)

export const getLocalUsuarioLocalApiListarUsuariosConLocalesUrl = (params?: LocalUsuarioLocalApiListarUsuariosConLocalesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/locales/usuario-local/listar?${stringifiedParams}` : `/api/locales/usuario-local/listar`
}

export const localUsuarioLocalApiListarUsuariosConLocales = async (params?: LocalUsuarioLocalApiListarUsuariosConLocalesParams, options?: RequestInit): Promise<localUsuarioLocalApiListarUsuariosConLocalesResponse> => {
  
  const res = await fetch(getLocalUsuarioLocalApiListarUsuariosConLocalesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: localUsuarioLocalApiListarUsuariosConLocalesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as localUsuarioLocalApiListarUsuariosConLocalesResponse
}



/**
 * @summary Asignar Local A Usuario
 */
export type localUsuarioLocalApiAsignarLocalAUsuarioResponse200 = {
  data: UsuarioConLocalesSchema
  status: 200
}
    
export type localUsuarioLocalApiAsignarLocalAUsuarioResponseSuccess = (localUsuarioLocalApiAsignarLocalAUsuarioResponse200) & {
  headers: Headers;
};
;

export type localUsuarioLocalApiAsignarLocalAUsuarioResponse = (localUsuarioLocalApiAsignarLocalAUsuarioResponseSuccess)

export const getLocalUsuarioLocalApiAsignarLocalAUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/locales/usuario-local/asignar/${usuarioId}`
}

export const localUsuarioLocalApiAsignarLocalAUsuario = async (usuarioId: number,
    usuarioLocalPayloadSchema: UsuarioLocalPayloadSchema, options?: RequestInit): Promise<localUsuarioLocalApiAsignarLocalAUsuarioResponse> => {
  
  const res = await fetch(getLocalUsuarioLocalApiAsignarLocalAUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioLocalPayloadSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: localUsuarioLocalApiAsignarLocalAUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as localUsuarioLocalApiAsignarLocalAUsuarioResponse
}



/**
 * @summary Desasignar Local A Usuario
 */
export type localUsuarioLocalApiDesasignarLocalAUsuarioResponse200 = {
  data: UsuarioConLocalesSchema
  status: 200
}
    
export type localUsuarioLocalApiDesasignarLocalAUsuarioResponseSuccess = (localUsuarioLocalApiDesasignarLocalAUsuarioResponse200) & {
  headers: Headers;
};
;

export type localUsuarioLocalApiDesasignarLocalAUsuarioResponse = (localUsuarioLocalApiDesasignarLocalAUsuarioResponseSuccess)

export const getLocalUsuarioLocalApiDesasignarLocalAUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/locales/usuario-local/desasignar/${usuarioId}`
}

export const localUsuarioLocalApiDesasignarLocalAUsuario = async (usuarioId: number,
    usuarioLocalPayloadSchema: UsuarioLocalPayloadSchema, options?: RequestInit): Promise<localUsuarioLocalApiDesasignarLocalAUsuarioResponse> => {
  
  const res = await fetch(getLocalUsuarioLocalApiDesasignarLocalAUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioLocalPayloadSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: localUsuarioLocalApiDesasignarLocalAUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as localUsuarioLocalApiDesasignarLocalAUsuarioResponse
}
