/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  LoginResponseSchema,
  LoginSchema
} from './schemas';

/**
 * @summary Login
 */
export type authApiLoginResponse200 = {
  data: LoginResponseSchema
  status: 200
}
    
export type authApiLoginResponseSuccess = (authApiLoginResponse200) & {
  headers: Headers;
};
;

export type authApiLoginResponse = (authApiLoginResponseSuccess)

export const getAuthApiLoginUrl = () => {


  

  return `/api/auth/login`
}

export const authApiLogin = async (loginSchema: LoginSchema, options?: RequestInit): Promise<authApiLoginResponse> => {
  
  const res = await fetch(getAuthApiLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authApiLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authApiLoginResponse
}
