/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type { LocalEstadisticasSchema } from './localEstadisticasSchema';

export interface DashboardSchema {
  cuenta_nombre: string;
  total_productos: number;
  total_locales_accesibles: number;
  total_conteos_borrador: number;
  total_conteos_finalizados: number;
  productos_a_comprar_hoy: number;
  locales: LocalEstadisticasSchema[];
}
