/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface LocalEstadisticasSchema {
  local_id: number;
  local_nombre: string;
  productos_en_plantilla: number;
  ultimo_conteo_fecha?: string | null;
  ultimo_conteo_estado?: string | null;
  total_conteos: number;
  productos_a_comprar_hoy: number;
}
