/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface UnidadMedidaSchema {
  id?: number | null;
  /** @maxLength 50 */
  nombre: string;
  created_at: string;
  updated_at: string;
}
