/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export * from './input';
export * from './pagedPlantillaStockSchema';
export * from './plantillastockApiListarPlantillasParams';
export * from './plantillaStockCreateSchema';
export * from './plantillaStockSchema';
export * from './plantillaStockUpdateSchema';