/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type { PlantillaStockSchema } from './plantillaStockSchema';

export interface PagedPlantillaStockSchema {
  items: PlantillaStockSchema[];
  count: number;
}
