/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface PlantillaStockSchema {
  id: number;
  local_id: number;
  producto_id: number;
  producto_nombre: string;
  producto_unidad_medida: string;
  cantidad_objetivo: number;
  created_at: string;
  updated_at: string;
}
