/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface PlantillaStockCreateSchema {
  local_id: number;
  producto_id: number;
  cantidad_objetivo: number;
}
