/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface UsuarioSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  cuenta: number;
  /** @maxLength 255 */
  email: string;
  es_admin?: boolean;
}
