/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */

export interface UsuarioCambiarMiContrasenaSchema {
  password_actual: string;
  nueva_password: string;
}
