/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * NinjaAPI
 * OpenAPI spec version: 1.0.0
 */
import type {
  PagedPlantillaStockSchema,
  PlantillaStockCreateSchema,
  PlantillaStockSchema,
  PlantillaStockUpdateSchema,
  PlantillastockApiListarPlantillasParams
} from './schemas';

/**
 * @summary Listar Plantillas
 */
export type plantillastockApiListarPlantillasResponse200 = {
  data: PagedPlantillaStockSchema
  status: 200
}
    
export type plantillastockApiListarPlantillasResponseSuccess = (plantillastockApiListarPlantillasResponse200) & {
  headers: Headers;
};
;

export type plantillastockApiListarPlantillasResponse = (plantillastockApiListarPlantillasResponseSuccess)

export const getPlantillastockApiListarPlantillasUrl = (params?: PlantillastockApiListarPlantillasParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/plantillas-stock/listar?${stringifiedParams}` : `/api/plantillas-stock/listar`
}

export const plantillastockApiListarPlantillas = async (params?: PlantillastockApiListarPlantillasParams, options?: RequestInit): Promise<plantillastockApiListarPlantillasResponse> => {
  
  const res = await fetch(getPlantillastockApiListarPlantillasUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: plantillastockApiListarPlantillasResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as plantillastockApiListarPlantillasResponse
}



/**
 * @summary Crear Plantilla
 */
export type plantillastockApiCrearPlantillaResponse200 = {
  data: PlantillaStockSchema
  status: 200
}
    
export type plantillastockApiCrearPlantillaResponseSuccess = (plantillastockApiCrearPlantillaResponse200) & {
  headers: Headers;
};
;

export type plantillastockApiCrearPlantillaResponse = (plantillastockApiCrearPlantillaResponseSuccess)

export const getPlantillastockApiCrearPlantillaUrl = () => {


  

  return `/api/plantillas-stock/crear`
}

export const plantillastockApiCrearPlantilla = async (plantillaStockCreateSchema: PlantillaStockCreateSchema, options?: RequestInit): Promise<plantillastockApiCrearPlantillaResponse> => {
  
  const res = await fetch(getPlantillastockApiCrearPlantillaUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      plantillaStockCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: plantillastockApiCrearPlantillaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as plantillastockApiCrearPlantillaResponse
}



/**
 * @summary Actualizar Plantilla
 */
export type plantillastockApiActualizarPlantillaResponse200 = {
  data: PlantillaStockSchema
  status: 200
}
    
export type plantillastockApiActualizarPlantillaResponseSuccess = (plantillastockApiActualizarPlantillaResponse200) & {
  headers: Headers;
};
;

export type plantillastockApiActualizarPlantillaResponse = (plantillastockApiActualizarPlantillaResponseSuccess)

export const getPlantillastockApiActualizarPlantillaUrl = (plantillaId: number,) => {


  

  return `/api/plantillas-stock/actualizar/${plantillaId}`
}

export const plantillastockApiActualizarPlantilla = async (plantillaId: number,
    plantillaStockUpdateSchema: PlantillaStockUpdateSchema, options?: RequestInit): Promise<plantillastockApiActualizarPlantillaResponse> => {
  
  const res = await fetch(getPlantillastockApiActualizarPlantillaUrl(plantillaId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      plantillaStockUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: plantillastockApiActualizarPlantillaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as plantillastockApiActualizarPlantillaResponse
}



/**
 * @summary Eliminar Plantilla
 */
export type plantillastockApiEliminarPlantillaResponse200 = {
  data: void
  status: 200
}
    
export type plantillastockApiEliminarPlantillaResponseSuccess = (plantillastockApiEliminarPlantillaResponse200) & {
  headers: Headers;
};
;

export type plantillastockApiEliminarPlantillaResponse = (plantillastockApiEliminarPlantillaResponseSuccess)

export const getPlantillastockApiEliminarPlantillaUrl = (plantillaId: number,) => {


  

  return `/api/plantillas-stock/eliminar/${plantillaId}`
}

export const plantillastockApiEliminarPlantilla = async (plantillaId: number, options?: RequestInit): Promise<plantillastockApiEliminarPlantillaResponse> => {
  
  const res = await fetch(getPlantillastockApiEliminarPlantillaUrl(plantillaId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: plantillastockApiEliminarPlantillaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as plantillastockApiEliminarPlantillaResponse
}
